//
//  NWmodel.swift
//  AMTfm
//
//  Created by DEEBA on 07.05.20.
//  Copyright © 2020 Dabus.tv. All rights reserved.
//

import Foundation
struct nwMdl
{
    var DisNm:[String]
    var TmNam:[String]
    var EqNam:[String]
    var Caus:[String]
    var EqLcn:[String]
    var Prioritz:[String]
    var dtSchedule:[String]
    var idee:[String]
    var idTbl:[Int]
    var display_nameTbl:[String]
    var causeTbl:[String]
    var mAssignedByTbl:[String]
    var stateTbl:[String]
    var date_scheduledTbl:[String]
    var type_categoryTbl:[String]
    var equipment_location_namTbl:[String]
    var priorityTbl:[String]
    var mAssignedToTbl:[String]
    var mAssetNamTbl:[String]
    var maintenance_typeTbl:[String]
    var mStarttmTbl:[String]
    var mEndtmTbl:[String]
    var StatuzTbl:[Bool]
    var boolz1Tbl:[Bool]
    var boolz2Tbl:[Bool]
    var mCompanyNamTbl:[String]
    var strchkListTbl:[String]
    var at_start_mroTbl:[Bool]
    var at_done_mroTbl:[Bool]
    var at_review_mroTbl:[Bool]
    var maintenance_team_idTbl:[String]
    var hlpDskId_idTbl:[String]
    var mAssetIdTbl:[String]
    var enforce_timeTbl:[Bool]
    var boolz3Tbl:[Bool]
    var strReasonTbl:[String]
    var strReasonIdTbl:[String]
    var strSelectdReasonTbl:[String]
    var QRcdeTbl:[String]
    var strMsgIdsTbl:[String]
init() {
        strMsgIdsTbl = []
         mAssetIdTbl = []
         QRcdeTbl = []
         DisNm = []
         TmNam = []
         EqNam = []
         Caus = []
         EqLcn = []
         Prioritz = []
         dtSchedule = []
         idee = []
         idTbl = []
         causeTbl = []
         stateTbl = []
         display_nameTbl = []
         mAssignedByTbl = []
         date_scheduledTbl = []
         type_categoryTbl = []
         equipment_location_namTbl = []
         priorityTbl = []
         mAssignedToTbl = []
         mAssetNamTbl = []
         maintenance_typeTbl = []
         mStarttmTbl = []
         mEndtmTbl = []
         StatuzTbl = []
         boolz1Tbl = []
         boolz2Tbl = []
         mCompanyNamTbl = []
         strchkListTbl = []
         at_start_mroTbl = []
         at_done_mroTbl = []
         at_review_mroTbl = []
         maintenance_team_idTbl = []
         hlpDskId_idTbl = []
         enforce_timeTbl = []
         boolz3Tbl = []
         strReasonTbl = []
         strReasonIdTbl = []
         strSelectdReasonTbl = []
    }
}
var nwOMdl = nwMdl()
